%dot_transient ........
%dot_op ............... If you want to run a DC sweep analysis, use dcsweep or dcsweep2.
%dot_ac ...............
%dot_tran .............
%run_transient_TRAP ... function LMSobj = run_transient_TRAP(DAE, xinit, tstart, tstep, ...
%transient ............ doStepControl, 'OptionName1', OptionVal1, 'OptionName2', OptionVal2, ...)
%dot_dc ............... If you want to run a DC sweep analysis, use dcsweep or dcsweep2.
%dcsweep2 ............. inpORparm2NAME,inpORparm2Range,IsInpORparm2, ...
%run_transient_ode15s . This usability function uses ODEXY with ode15s to solve the DAE.
%tr ...................
%ac ................... Run an AC analysis on a DAE.
%dcsweep .............. function QSSsweepObj = dcsweep(DAE, initguess, inpORparmNAME, ...
%op ................... Runs a DC operating point analysis on the given DAE.
%homotopy ............. maxLambdaStep, maxLambda, minLambda, maxArcLength)
%tran .................
%dot_dcsweep ..........
%dot_tr ...............
%run_transient_FE ..... function LMSobj = run_transient_FE(DAE, xinit, tstart, tstep, ...
%run_transient_GEAR2 .. function TransObjGEAR2 = run_transient_GEAR2(DAE, xinit, tstart, tstep, ...
%run_transient_BE ..... function LMSobj = run_transient_BE(DAE, xinit, tstart, tstep, ...
%dc ................... If you want to run a DC sweep analysis, use dcsweep or dcsweep2.
